%implement root finder using the Newton Method
%INPUTS:
%fun: the mathetmatical function we want to solve
%x0: the initial guess
%max_iter: limit of max iterations
% dxtol: termination threshold (stop when interval abs(dx) < dxtol)
% ftol: termination threshold (stop when abs(f)<ftol
% terminate when abs(-dx) > dxmax, where dxmax is a very large number
%OUTPUTS:
%x: approximate root of function
%flag: 1 is success, 0 is failure

%%%%%%%%%% ORION COMMENTS
%Your Implementation of Newton's method
%INPUTS:
%fun: the mathematical function for which we want to compute the root
%   note that the output of fun may include the derivative
%   i.e. [fval,dfdx] = fun(x)
%   or not, i.e. fval = fun(x)
%x_guess the initial guess for Newton's method
%solver_params: a MATLAB struct containing solver settings
%   solver_params.dxmin: terminate early if |x_{i+1}-x_{i}|<dxmin
%   solver_params.ftol: terminate early if |f(x_i)|<ftol
%   solver_params.max_iter: maximum number of iterations allowed
%   solver_params.dxmax: terminate early if |x_{i+1}-x_{i}|>dxmax
%       (meaning that jacobian is probably singular, which is bad)
%   solver_params.numerical_diff: boolean (0 or 1)
%           1-> numerically differentiate, 0-> use analytical derivative
%should use numerical differentation to compute the Jacobian or
%use a Jacobian generated by fun. No input assumes numerical by default
%   true->fun is assumed to return [fval,J]
%   false->fun is assumed to only return fval
%OUTPUTS:
%x: the estimate of the root computed by the function
% exit_flag: an integer indicating whether or not the solver succeeded
%%%%%%%%%%%%%%%

function [x,flag] = newton_solver2(fun,X0,max_iter,ftol,dxtol,dx_max)
    for i = 1:max_iter
        [F,J] = fun(X0);
        
        if abs(f) < ftol
            %fprintf('ftol\n');
            x = X0;
            %flag = 1;
            return
        end

        dx = -F*(J\F);
        
        if abs(dx) > dx_max
            %dx = sign(dx)*dx_max;
            %flag = 0; 
            x = X0;
            return
        end

        X1=X0+dx;

        if abs(dx) <= dxtol
            %fprintf('dxtol\n');
            x = X1;
            %flag = 1;
            return
        end

        X0 = X1;
        hold on
    end
    x = X0
    %flag = 0;
    %fprintf('max_iter\n')
end